apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit
          image: bindudevidas/streamlit-devops-lab:v1
          ports:
            - containerPort: 8501
          env:
            - name: APP_ENV
              value: "k8s"
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10