name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ GitHub Actions is running for $GITHUB_REPOSITORY (commit $GITHUB_SHA)"
