name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Compile Python (syntax check)
        run: python -m compileall -q .
      - name: Streamlit import smoke test
        run: python - <<'PY'
        import streamlit as st
        print("Streamlit OK:", st.__version__)
        PY